server {
  listen 80;
  listen [::]:80;
  server_name gavior.in www.gavior.in;
  client_max_body_size 25m;

  location /.well-known/acme-challenge/ { root /var/www/certbot; }
  location / { return 301 https://$host$request_uri; }
}
